/home/bitnami/logs/*.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    maxsize 10M
    copytruncate
}

/home/bitnami/log_do_motor.txt /home/bitnami/log_scrapers.txt {
    daily
    rotate 3
    compress
    missingok
    notifempty
    maxsize 10M
    copytruncate
}
